# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# -------------------------------------------------------
# Site setting
# -------------------------------------------------------

title: GDSC DEU
email: gdsc.kr.deu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Google Developer Student Clubs Dong-Eui University(GDSC DEU)는 Google 기술에 관심있는 학생들을 위한 대학교 기반 커뮤니티 그룹입니다. 다양한 학문적 배경을 가진 학생들이 모여 AI, ML, 클라우드, 안드로이드, 플러터 등 최신 기술을 학습하고, 프로젝트와 해커톤을 통해 실력을 키우며 성장하는 것을 목표로 합니다.
domain: gdsc-deu.github.io
url: "https://gdsc-deu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jekyllrb
github_username:  GDSC-DEU
timezone: Asia/Seoul

# -------------------------------------------------------
# Collection setting
# -------------------------------------------------------
collections:
  members:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

include: ['_pages']

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
